/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "bspatch.h"

/* Header for class Java_com_dodola_patcher_utils_AppUtils */

#ifndef _Included_com_dodola_patcher_MainActivity
#define _Included_com_dodola_patcher_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com.dodola.patcher.utils.AppUtils
 * Method:    patcher
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_dodola_patcher_utils_AppUtils_patcher
  (JNIEnv *, jobject, jstring argv1, jstring argv2, jstring argv3);

#ifdef __cplusplus
}
#endif
#endif
